### PR TITLE
Update Prebid Universal Creative snippet to include `hbPb` in tag data

### PR DESCRIPTION
**Pull request by lucop1**
Update the DFP Creative snipped based on the new one:

https://github.com/prebid/prebid-universal-creative#usage

### CODE REVIEW

**Comment by kmjennison** [comment]
@lucop1 It looks like your diff didn't actually change any code but just its indentation. Let me know if I'm missing something.

**Comment by lucop1** [comment]
I've added this parameter that is missing from the current template:
`ucTagData.hbPb = "%%PATTERN:hb_pb%%";`

**Comment by kmjennison** [comment]
Ah, sorry for overlooking that addition.

**Comment by kmjennison** [comment]
@lucop1 Thank you for the contribution!

**Pull request merged**
