### PR TITLE
Use universal creative

### LINKED ISSUE #73: Switch to Prebid's "universal creative"
See: http://prebid.org/overview/prebid-universal-creative.html

### PR DESCRIPTION
**Pull request by dlackty**
I've used this for a while for our AMP banners, and decided to send a PR. This closes #73.

### CODE REVIEW

**Comment by kmjennison** [comment]
@dlackty Thank you for the contribution!

**Comment by Austinb** [comment]
FYI the creative merged is incomplete.  Missing the `hb_pb` value - http://prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html#html-creative

**Comment by kmjennison** [comment]
@Austinb Thanks. I think the Prebid website docs are out of date. The universal creative code (linked as "latest version" from the Prebid docs) show that `hb_pb` isn't necessary on DFP:
https://github.com/prebid/prebid-universal-creative/blob/master/template/amp/dfp-creative.html

**Comment by Austinb** [comment]
If it is not needed any more that is fine it was that the version merged in did not match the docs from prebid or from the universal creative link. 

Also from https://github.com/prebid/prebid-universal-creative/blob/master/template/amp/dfp-creative.html - Last entry before `try {` in the link above `ucTagData.hbPb = "%%PATTERN:hb_pb%%";`.

**Comment by adops-tcs** [comment]
Does this universal code work with "send all bids" scenario? the documentaton on prebid.org says otherwise. 

```
<script src="https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js"></script>
<script>
  var ucTagData = {};
  ucTagData.adServerDomain = "";
  ucTagData.pubUrl = "%%PATTERN:url%%";
  ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;

  try {
    ucTag.renderAd(document, ucTagData);
  } catch (e) {
    console.log(e);
  }
</script>

```

**Comment by kmjennison** [comment]
@adops-tcs That's correct. The Prebid universal creative Github page [also mentions this](https://github.com/prebid/prebid-universal-creative#usage). For a "send all bids" setup, you'd want to use [this creative](http://prebid.org/adops/send-all-bids-adops.html#step-3-add-a-creative).

Note that when "send all bids" is enabled, Prebid still sends `hb_bidder` and `hb_pb` keys, so the default universal creative still works to select the correct line item.

**Comment by adops-tcs** [comment]
Thank you for your explanation @kmjennison ! However, I am still confused.  It understood the **dfp-prebid-setup** code to be made for "send all bids" scenario since it's designed to create a set of line items per each bidder.  However, the creative snippet is not what should be used for "send all bids".  Can you clarify please?   This is the creative snippet from one of the auto-generated creatives.  It's also missing _ucTagData.hbPb = "%%PATTERN:hb_pb%%";_ line.

`<script src="https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js"></script>
<script>
  var ucTagData = {};
  ucTagData.adServerDomain = "";
  ucTagData.pubUrl = "%%PATTERN:url%%";
  ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;

  try {
    ucTag.renderAd(document, ucTagData);
  } catch (e) {
    console.log(e);
  }
</script>`

**Comment by kmjennison** [comment]
@adops-tcs The `hb_pb` isn't necessary in the creative for GAM (see [this comment](https://github.com/kmjennison/dfp-prebid-setup/pull/74#issuecomment-534724498) above).

You're correct that this tool creates an order per bidder. However, those line items are targeted on the general `hb_bidder` and `hb_pb` key-values, *not* on any bidder-specific keys like `hb_bidder_appnexus`. That means GAM will only match line items for the winning bids. It won't consider any of the other targeting provided by "send all bids".

I'm curious if you'd find the full "send all bids" setup helpful for some reason, such as reporting in GAM. If so, we can create an issue for it.

**Comment by adops-tcs** [comment]
It makes sense now, thanks again @kmjennison !    I actually modified the code as suggested here (https://github.com/kmjennison/dfp-prebid-setup/issues/18#issuecomment-341961387) to create one set of line items for all bidders.   I was confused on "send all bids" part because I had been researching that option as well and saw the creative snippet not matching.  It's all good now.

**Pull request merged**
